#!/bin/bash
if [ $# -eq 0 ]; then
  echo "Usage: $0 <DNSDOMAIN>"
  echo "e.g. $0 example.com"
  exit 1
else
  STACK_NAME=`echo $1 | sed -e 's/\./\-/g'`
  # Configures the aws-cli, requires an access key id and secret
  aws configure --profile default
  # Creates a CloudFormation stack for the s3 bucket website
  aws cloudformation create-stack \
    --stack-name www-$STACK_NAME \
    --template-body file://template.json \
    --capabilities CAPABILITY_IAM \
    --parameters ParameterKey=DomainName,ParameterValue=$1
fi
