#!/bin/bash
if [ $# -eq 0 ]; then
  echo "Usage: $0 create|update <DNSDOMAIN>"
  echo "e.g. $0 create example.com"
  exit 1
else
  STACK_NAME=`echo $2 | sed -e 's/\./\-/g'`
  export AWS_DEFAULT_PROFILE=www-$STACK_NAME 

  # Configures the aws-cli, requires an access key id and secret
  aws configure --profile $AWS_DEFAULT_PROFILE

  # Creates a CloudFormation stack for the s3 bucket website
  aws cloudformation $1-stack \
    --stack-name $AWS_DEFAULT_PROFILE \
    --template-body file://template.json \
    --capabilities CAPABILITY_IAM \
    --parameters ParameterKey=DomainName,ParameterValue=$2
fi
