#!/bin/bash
if [ $# -eq 0 ]; then
  echo "Usage: $0 create|update|delete <DOMAIN_NAME>"
  echo "e.g. $0 create|update|delete example.com"
  exit 1
else
  # Create a stack name based on the DomainName
  # Cloudformation doesn't accept periods in names
  export AWS_DEFAULT_PROFILE=`echo $2 | sed -e 's/\./\-/g'`
  
  # Configures the aws-cli, requires an access key id and secret
  aws configure --profile $AWS_DEFAULT_PROFILE
  
  if [ "$1" != "delete" ]; then
    # Creates a CloudFormation stack for the s3 bucket website
    aws cloudformation $1-stack \
      --stack-name $AWS_DEFAULT_PROFILE \
      --template-body file://template.json \
      --capabilities CAPABILITY_IAM \
      --parameters ParameterKey=DomainName,ParameterValue=$2
  else
    aws cloudformtation delete-stack --stack-name $AWS_DEFAULT_PROFILE
  fi
fi
